// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Files = sequelize.define('files', {
    url: {
      type: DataTypes.STRING,
    },
    transcript: {
      type: DataTypes.STRING,
    },
    translationFr: {
      type: DataTypes.STRING,
    },
    language: {
      type: DataTypes.STRING,
    },
    comment: {
      type: DataTypes.STRING,
    },
    personsPosition: {
      type: DataTypes.STRING,
    },
    originalFormat: {
      type: DataTypes.STRING,
    },
    color: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'files',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Files.associate = (models) => {
    Files.belongsTo(models.documents, {
      foreignKey: {
        name: 'documentIdKey',
        field: 'document_id',
      },
      as: 'document',
    });
  };

  return Files;
};
